name: build (auditwheel)

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Package version'
        required: true
        default: 'latest'
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    name: Build auditwheel ${{ github.event.inputs.app_version || 'latest' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get versions
        run: |
          package=auditwheel
          version=${{ github.event.inputs.app_version || 'latest' }}
          if [ "${version}" = "latest" ]; then
            version=$(curl -sSL "https://pypi.org/pypi/${package}/json" | jq -r '.info.version')
          fi
          echo "Found version: $version"

          if curl "https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple/${package}" | grep -oP '(?<=>)[^<]+\.whl' | grep -q "auditwheel-${version}-py3-none-any.whl"; then
            echo "Package ${package} ${version} already exists"
            echo "BUILD=false" >> $GITHUB_ENV
            exit 0
          fi
          full_json=$(curl -sSL "https://pypi.org/pypi/${package}/${version}/json")
          download_url=$(echo "$full_json" | jq -r '.urls[] | select(.packagetype=="sdist").url')
          if [ -z "$download_url" ]; then
            echo "No source found for package ${package} version ${version}"
            exit 1
          fi
          wget -O - "$download_url" | tar xz --strip-components=1
          ## https://github.com/pypa/auditwheel/pull/522
          # wget -O - https://github.com/loong64/auditwheel/commit/c4f57287c7e766d26931f7b65e0163a32cd686b0.patch | patch -p1

      - name: Set python
        if: env.BUILD != 'false'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Wheel build
        if: env.BUILD != 'false'
        run: |
          pip wheel . --wheel-dir=/tmp/cibuildwheel/built_wheel --no-deps

      - name: Upload wheels
        if: env.BUILD != 'false'
        run: |
          pip install twine==6.0.1
          twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi /tmp/cibuildwheel/built_wheel/*.whl
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}
