name: Auto Multi-Build Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - id: set-packages
        run: |
          cd project || exit 1
          PACKAGES=$(ls -d */ | while read -r dir; do
            if [ -f "${dir}/multi" ]; then
              echo "${dir%/}"
            fi
          done | jq -R -s -c 'split("\n")[:-1]')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare.outputs.packages) }}
        platform: ['cp39-manylinux_*', 'cp310-manylinux_*', 'cp311-manylinux_*', 'cp312-manylinux_*', 'cp313-manylinux_*']
    steps:
      - name: Build Package
        uses: loong64/pypi@master
        with:
          app_name: ${{ matrix.package }}
          app_arch: 'loongarch64'
          app_platform: 

      - name: Upload wheels
        run: |
          pip install twine
          for file in wheelhouse/*.whl; do
            twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi $file || true
          done
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}
