name: Custom Build Package

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Package name to build'
        required: true
        default: ''
      app_version:
        description: 'Package version pattern'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get versions
        id: get-versions
        run: |
          package=${{ github.event.inputs.app_name }}
          version=${{ github.event.inputs.app_version }}
          if [ "$version" = "latest" ]; then
            version=$(curl -sSL "https://pypi.org/pypi/${package}/json" | jq -r '.info.version')
          fi
          echo "Building package: ${package} version: ${version}"
          echo "PIP_EXTRA_INDEX_URL=https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple" >> $GITHUB_ENV

          full_json=$(curl -sSL "https://pypi.org/pypi/${package}/${version}/json")
          download_url=$(echo "$full_json" | jq -r '.urls[] | select(.packagetype=="sdist").url')
          if [ -z "$download_url" ]; then
              echo "No source found for package ${package} version ${version}"
              exit 1
          fi
          wget -O - "$download_url" | tar xz --strip-components=1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: loong64/cibuildwheel@v3.2.0
        env:
          CIBW_ARCHS: loongarch64
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ENVIRONMENT_PASS_LINUX: PIP_EXTRA_INDEX_URL

      - name: Check wheel
        run: |
          ls -al wheelhouse/*.whl || exit 0
          echo "upload=true" >> $GITHUB_ENV

      - name: Upload wheels
        run: |
          pip install twine==6.0.1
          for file in wheelhouse/*.whl; do
            twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi $file || true
          done
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}
