name: build (gevent)

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        description: 'Package version'
        type: string
        required: true
  schedule:
    - cron: '0 18 * * *'

jobs:
  build_wheels:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - manylinux_2_38_loongarch64
          - musllinux_1_2_loongarch64

    name: ${{ matrix.image }}
    steps:
      - name: Get Source Code
        run: |
          package=gevent
          if [ "${{ github.event_name }}" = "schedule" ]; then
            version="latest"
          else
            version=${{ github.event.inputs.version }}
          fi
          if [ "$version" = "latest" ]; then
            version=$(curl -sSL "https://pypi.org/pypi/${package}/json" | jq -r '.info.version')
          fi
          echo "Building package: ${package} version: ${version}"
          echo "PIP_EXTRA_INDEX_URL=https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple" >> $GITHUB_ENV

          if curl "https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple/${package//./-}" | grep -oP '(?<=>)[^<]+\.whl' | grep -q "${package}-${version}-.*_loongarch64.whl"; then
            echo "Package ${package} ${version} already exists"
            echo "BUILD=false" >> $GITHUB_ENV
            exit 0
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Checkout
        if: env.BUILD != 'false'
        uses: actions/checkout@v6
        with:
          repository: gevent/gevent
          ref: ${{ env.VERSION }}

      - name: Setup QEMU
        if: env.BUILD != 'false'
        uses: docker/setup-qemu-action@v4

      - name: Cache ~/.ccache
        uses: actions/cache@v6
        with:
          path: ~/.ccache/**
          key: ${{ runner.os }}-gevent-ccache_${{ matrix.image }}

      - name: Build and test gevent
        if: env.BUILD != 'false'
        env:
          DOCKER_IMAGE: ghcr.io/loong64/${{ matrix.image }}
          GEVENT_MANYLINUX_NAME: ${{ matrix.image }}
          PIP_UPGRADE_STRATEGY: eager
          # Higher values like 2 definitely cause test breakage, as we
          # can't stop a libev watcher if the FD has been closed (which is
          # a silly design decision)
          GEVENTSETUP_EV_VERIFY: 1
          # Disable some warnings produced by libev especially and also some Cython generated code.
          # These are shared between GCC and clang so it must be a minimal set.
          # TODO: Figure out how to set env vars per platform without resorting to inline scripting.
          # Note that changing the value of these variables invalidates configure caches
          CFLAGS: -O3 -pipe -Wno-strict-aliasing -Wno-comment
          CPPFLAGS: -DEV_VERIFY=1
          ###
          # caching
          ###
          # CCACHE_DIR: ~/.ccache # Using ~ here makes it not find its cache.
          CC: "ccache gcc"
          CCACHE_NOCPP2: true
          CCACHE_SLOPPINESS: file_macro,time_macros,include_file_ctime,include_file_mtime
          CCACHE_NOHASHDIR: true
        run: |
          sed -i 's@GEVENT_MANYLINUX_NAME@PIP_EXTRA_INDEX_URL -e GEVENT_MANYLINUX_NAME@g' scripts/releases/make-manylinux
          # Disable python-3.15 build
          # https://github.com/gevent/gevent/pull/2190
          # sed -i 's/ --no-binary :all://g' scripts/releases/make-manylinux
          # sed -i 's/315,314,/314,/g' scripts/releases/make-manylinux
          scripts/releases/make-manylinux

      - name: Check wheel
        run: |
          ls -al wheelhouse/*.whl || exit 0
          echo "upload=true" >> $GITHUB_ENV

      - name: Upload wheels
        if: env.upload == 'true'
        run: |
          pip install twine==6.0.1
          for file in wheelhouse/*.whl; do
            twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi $file || true
          done
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}