name: build (greenlet)

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        description: 'Package version'
        type: string
        required: true
  schedule:
    - cron: '0 17 * * *'

jobs:
  build_wheels:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        image:
          - quay.io/pypa/manylinux2014_aarch64
          - quay.io/pypa/manylinux2014_ppc64le
          - quay.io/pypa/manylinux2014_s390x
          - quay.io/pypa/manylinux2014_x86_64
          - quay.io/pypa/manylinux_2_28_aarch64
          - quay.io/pypa/manylinux_2_28_ppc64le
          - quay.io/pypa/manylinux_2_28_s390x
          - quay.io/pypa/manylinux_2_28_x86_64
          - ghcr.io/loong64/manylinux_2_38_loongarch64
          - quay.io/pypa/musllinux_1_2_aarch64
          - ghcr.io/loong64/musllinux_1_2_loongarch64
          - quay.io/pypa/musllinux_1_2_ppc64le
          - quay.io/pypa/musllinux_1_2_s390x
          - quay.io/pypa/musllinux_1_2_x86_64

    name: ${{ matrix.image }}
    steps:
      - name: Get Source Code
        run: |
          package=greenlet
          if [ "${{ github.event_name }}" = "schedule" ]; then
            version="latest"
          else
            version=${{ github.event.inputs.version }}
          fi
          if [ "$version" = "latest" ]; then
            version=$(curl -sSL "https://pypi.org/pypi/${package}/json" | jq -r '.info.version')
          fi
          echo "Building package: ${package} version: ${version}"
          echo "PIP_EXTRA_INDEX_URL=https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple" >> $GITHUB_ENV

          if curl "https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple/${package/./-}" | grep -oP '(?<=>)[^<]+\.whl' | grep -q "${package}-${version}-.*_loongarch64.whl"; then
            echo "Package ${package} ${version} already exists"
            echo "BUILD=false" >> $GITHUB_ENV
            exit 0
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: checkout
        if: env.BUILD != 'false'
        uses: actions/checkout@v4
        with:
          repository: python-greenlet/greenlet
          ref: ${{ env.VERSION }}

      - name: Set up Python ${{ matrix.python-version }}
        if: env.BUILD != 'false'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup QEMU
        if: env.BUILD != 'false'
        uses: docker/setup-qemu-action@v3

      - name: Build and test greenlet
        if: env.BUILD != 'false'
        env:
          DOCKER_IMAGE: ${{ matrix.image }}
        run: bash ./make-manylinux

      - name: Check wheel
        run: |
          ls -al wheelhouse/*.whl || exit 0
          echo "upload=true" >> $GITHUB_ENV

      - name: Upload wheels
        if: env.upload == 'true'
        run: |
          pip install twine==6.0.1
          for file in wheelhouse/*.whl; do
            twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi $file || true
          done
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}