name: build (torch)

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Build version'
        required: true
        default: ''

jobs:
  build:
    name: 'Build ${{ matrix.package }}-${{ inputs.app_version }}-${{ matrix.platform }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['torch']
        platform: ['cp39-manylinux_*', 'cp310-manylinux_*', 'cp311-manylinux_*', 'cp312-manylinux_*', 'cp313-manylinux_*']
    steps:
      - name: Checkout Code
        run: |
          app_version=${{ github.event.inputs.app_version }}
          wget -O - https://github.com/pytorch/pytorch/releases/download/${app_version}/pytorch-${app_version}.tar.gz | tar xz --strip-components=1

          cd third_party/sleef
          wget -O - https://github.com/loong64/pypi/raw/refs/heads/master/patch/torch/sleef_loong64.patch | patch -p1

          echo "PYTORCH_BUILD_NUMBER=1" >> $GITHUB_ENV
          echo "PYTORCH_BUILD_VERSION=${app_version/v/}" >> $GITHUB_ENV

      - name: Setup QEMU
        run: docker run --rm --privileged ghcr.io/loong64/qemu-user-static --reset -p yes

      - name: Build wheels
        uses: loong64/cibuildwheel@main
        env:
          CIBW_MANYLINUX_LOONGARCH64_IMAGE: manylinux_2_38
          CIBW_ARCHS: loongarch64
          CIBW_BUILD: ${{ matrix.platform }}
          CIBW_TEST_SKIP: "*"
          CIBW_BEFORE_ALL_LINUX: "curl -sSf https://sh.rustup.rs | sh -s -- -y"
          CIBW_ENVIRONMENT_LINUX: >
            BUILD_TEST=0
            PYTORCH_BUILD_NUMBER=${{ env.PYTORCH_BUILD_NUMBER }}
            PYTORCH_BUILD_VERSION=${{ env.PYTORCH_BUILD_VERSION }}
            PIP_EXTRA_INDEX_URL="https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple"
            PATH="$HOME/.cargo/bin:$PATH"

      - name: Upload wheels
        run: |
          pip install twine==6.0.1
          twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi wheelhouse/*.whl
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}