name: build (xmlsec)

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        description: 'Package version'
        type: string
        required: true
  schedule:
    - cron: '0 15 * * *'

jobs:
  manylinux:
    runs-on: ${{ matrix.MANYLINUX.RUNNER }}
    strategy:
      fail-fast: false
      matrix:
        MANYLINUX:
          - { NAME: "manylinux2014_x86_64", CONTAINER: "xmlsec-manylinux2014:x86_64", RUNNER: "ubuntu-24.04" }
          - { NAME: "manylinux_2_28_x86_64", CONTAINER: "xmlsec-manylinux_2_28:x86_64", RUNNER: "ubuntu-24.04" }
          - { NAME: "musllinux_1_2_x86_64", CONTAINER: "xmlsec-musllinux_1_2:x86_64", RUNNER: "ubuntu-24.04" }

          - { NAME: "manylinux2014_aarch64", CONTAINER: "xmlsec-manylinux2014:aarch64", RUNNER: "ubuntu-24.04-arm" }
          - { NAME: "manylinux_2_28_aarch64", CONTAINER: "xmlsec-manylinux_2_28:aarch64", RUNNER: "ubuntu-24.04-arm" }
          - { NAME: "musllinux_1_2_aarch64", CONTAINER: "xmlsec-musllinux_1_2:aarch64", RUNNER: "ubuntu-24.04-arm" }

          - { NAME: "manylinux2014_ppc64le", CONTAINER: "xmlsec-manylinux2014:ppc64le", RUNNER: "ubuntu-24.04" }
          - { NAME: "manylinux_2_28_ppc64le", CONTAINER: "xmlsec-manylinux_2_28:ppc64le", RUNNER: "ubuntu-24.04" }
          - { NAME: "musllinux_1_2_ppc64le", CONTAINER: "xmlsec-musllinux_1_2:ppc64le", RUNNER: "ubuntu-24.04" }

          - { NAME: "manylinux2014_s390x", CONTAINER: "xmlsec-manylinux2014:s390x", RUNNER: "ubuntu-24.04" }
          - { NAME: "manylinux_2_28_s390x", CONTAINER: "xmlsec-manylinux_2_28:s390x", RUNNER: "ubuntu-24.04" }
          - { NAME: "musllinux_1_2_s390x", CONTAINER: "xmlsec-musllinux_1_2:s390x", RUNNER: "ubuntu-24.04" }

          - { NAME: "manylinux_2_38_loongarch64", CONTAINER: "xmlsec-manylinux_2_38:loongarch64", RUNNER: "ubuntu-24.04" }
          - { NAME: "musllinux_1_2_loongarch64", CONTAINER: "xmlsec-musllinux_1_2:loongarch64", RUNNER: "ubuntu-24.04" }


    steps:
      - name: Get Source Code
        run: |
          package=xmlsec
          if [ "${{ github.event_name }}" = "schedule" ]; then
            version="latest"
          else
            version=${{ github.event.inputs.version }}
          fi
          if [ "$version" = "latest" ]; then
            version=$(curl -sSL "https://pypi.org/pypi/${package}/json" | jq -r '.info.version')
          fi
          echo "Building package: ${package} version: ${version}"
          echo "PIP_EXTRA_INDEX_URL=https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple" >> $GITHUB_ENV

          case "${{ matrix.MANYLINUX.NAME }}" in
            manylinux2014_x86_64)
              check_file="${package}-${version}-.*manylinux2014_x86_64.whl"
              echo "CIBW_ARCHS=x86_64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_x86_64" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_X86_64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux_2_28_x86_64)
              check_file="${package}-${version}-.*manylinux_2_28_x86_64.whl"
              echo "CIBW_ARCHS=x86_64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_x86_64" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_X86_64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            musllinux_1_2_x86_64)
              check_file="${package}-${version}-.*musllinux_1_2_x86_64.whl"
              echo "CIBW_ARCHS=x86_64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-musllinux_x86_64" >> $GITHUB_ENV
              echo "CIBW_MUSLLINUX_X86_64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux2014_aarch64)
              check_file="${package}-${version}-.*manylinux2014_aarch64.whl"
              echo "CIBW_ARCHS=aarch64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_aarch64" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_AARCH64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux_2_28_aarch64)
              check_file="${package}-${version}-.*manylinux_2_28_aarch64.whl"
              echo "CIBW_ARCHS=aarch64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_aarch64" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_AARCH64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            musllinux_1_2_aarch64)
              check_file="${package}-${version}-.*musllinux_1_2_aarch64.whl"
              echo "CIBW_ARCHS=aarch64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-musllinux_aarch64" >> $GITHUB_ENV
              echo "CIBW_MUSLLINUX_AARCH64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux2014_ppc64le)
              check_file="${package}-${version}-.*manylinux2014_ppc64le.whl"
              echo "CIBW_ARCHS=ppc64le" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_ppc64le" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_PPC64LE_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux_2_28_ppc64le)
              check_file="${package}-${version}-.*manylinux_2_28_ppc64le.whl"
              echo "CIBW_ARCHS=ppc64le" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_ppc64le" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_PPC64LE_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            musllinux_1_2_ppc64le)
              check_file="${package}-${version}-.*musllinux_1_2_ppc64le.whl"
              echo "CIBW_ARCHS=ppc64le" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-musllinux_ppc64le" >> $GITHUB_ENV
              echo "CIBW_MUSLLINUX_PPC64LE_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux2014_s390x)
              check_file="${package}-${version}-.*manylinux2014_s390x.whl"
              echo "CIBW_ARCHS=s390x" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_s390x" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_S390X_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux_2_28_s390x)
              check_file="${package}-${version}-.*manylinux_2_28_s390x.whl"
              echo "CIBW_ARCHS=s390x" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_s390x" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_S390X_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            musllinux_1_2_s390x)
              check_file="${package}-${version}-.*musllinux_1_2_s390x.whl"
              echo "CIBW_ARCHS=s390x" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-musllinux_s390x" >> $GITHUB_ENV
              echo "CIBW_MUSLLINUX_S390X_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            manylinux_2_38_loongarch64)
              check_file="${package}-${version}-.*manylinux_2_38_loongarch64.whl"
              echo "CIBW_ARCHS=loongarch64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-manylinux_loongarch64" >> $GITHUB_ENV
              echo "CIBW_MANYLINUX_LOONGARCH64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            musllinux_1_2_loongarch64)
              check_file="${package}-${version}-.*musllinux_1_2_loongarch64.whl"
              echo "CIBW_ARCHS=loongarch64" >> $GITHUB_ENV
              echo "CIBW_BUILD=*-musllinux_loongarch64" >> $GITHUB_ENV
              echo "CIBW_MUSLLINUX_LOONGARCH64_IMAGE=ghcr.io/loong64/${{ matrix.MANYLINUX.CONTAINER }}" >> $GITHUB_ENV
              ;;
            *)
              echo "BUILD=false" >> $GITHUB_ENV
              exit 0
              ;;
          esac

          if curl "https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple/${package/./-}" | grep -oP '(?<=>)[^<]+\.whl' | grep -q "${check_file}"; then
            echo "Package ${package} ${version} already exists"
            echo "BUILD=false" >> $GITHUB_ENV
            exit 0
          fi

          full_json=$(curl -sSL "https://pypi.org/pypi/${package}/${version}/json")
          download_url=$(echo "$full_json" | jq -r '.urls[] | select(.packagetype=="sdist").url')
          if [ -z "$download_url" ]; then
              echo "No source found for package ${package} version ${version}"
              exit 1
          fi

          wget -O - "$download_url" | tar xz --strip-components=1

          if [ -f "pyproject.toml" ]; then
            sed -i 's/PYXMLSEC_STATIC_DEPS = "true"/# PYXMLSEC_STATIC_DEPS = "true""/g' pyproject.toml
          fi
          if [ -f "src/enc.c" ]; then
            sed -i 's/elem = PyXmlSec_elementFactory(doc, n);/elem = (PyXmlSec_LxmlElementPtr*)PyXmlSec_elementFactory(doc, n);/g' src/enc.c
          fi

      - name: Setup QEMU
        if: env.BUILD != 'false'
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        if: env.BUILD != 'false'
        uses: loong64/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ENVIRONMENT_PASS_LINUX: PIP_EXTRA_INDEX_URL
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_TEST_SKIP: "*"

      - name: Check wheel
        run: |
          ls -al wheelhouse/*.whl || exit 0
          echo "upload=true" >> $GITHUB_ENV

      - name: Upload wheels
        if: env.upload == 'true'
        run: |
          pip install twine==6.0.1
          for file in wheelhouse/*.whl; do
            twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi $file || true
          done
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}